# command cooldowns - in seconds
MINE_CD = 20
CHOP_CD = 15
ADVENTURE_CD = 60

# splashes for bot status
SPLASHES = [
    "As seen on TV!",
    "Awesome!",
    "100% pure!",
    "May contain nuts!",
    "More polygons!",
    "Moderately attractive!",
    "Limited edition!",
    "Flashing letters!",
    "It's here!",
    "Best in class!",
    "It's finished!",
    "Kind of dragon free!",
    "Excitement!",
    "More than 500 sold!",
    "One of a kind!",
    "Heaps of hits on YouTube!",
    "Indev!",
    "Spiders everywhere!",
    "Check it out!",
    "Holy cow, man!",
    "It's a game!",
    "Made in Sweden!",
    "Uses LWJGL!",
    "Reticulating splines!",
    "Minecraft!",
    "Yaaay!",
    "Singleplayer!",
    "Keyboard compatible!",
    "Ingots!",
    "Exploding creepers!",
    "That's no moon!",
    "l33t!",
    "Create!",
    "Survive!",
    "Dungeon!",
    "Exclusive!",
    "The bee's knees!",
    "Closed source!",
    "Classy!",
    "Wow!",
    "Not on steam!",
    "Oh man!",
    "Awesome community!",
    "Pixels!",
    "Teetsuuuuoooo!",
    "Kaaneeeedaaaa!",
    "Now with difficulty!",
    "Enhanced!",
    "90% bug free!",
    "Pretty!",
    "12 herbs and spices!",
    "Fat free!",
    "Absolutely no memes!",
    "Free dental!",
    "Ask your doctor!",
    "Cloud computing!",
    "Legal in Finland!",
    "Hard to label!",
    "Technically good!",
    "Bringing home the bacon!",
    "Indie!",
    "GOTY!",
    "Ceci n'est pas une title screen!",
    "Euclidian!",
    "Now in 3D!",
    "Inspirational!",
    "Herregud!",
    "Complex cellular automata!",
    "Yes, sir!",
    "Played by cowboys!",
    "Now on OpenGL 3.3 core profile!",
    "Now on Vulkan 1.2!",
    "Thousands of colors!",
    "Try it!",
    "Age of Wonders is better!",
    "Try the mushroom stew!",
    "Sensational!",
    "Hot tamale, hot hot tamale!",
    "Play him off, keyboard cat!",
    "Guaranteed!",
    "Macroscopic!",
    "Bring it on!",
    "Random splash!",
    "Call your mother!",
    "Monster infighting!",
    "Loved by millions!",
    "Ultimate edition!",
    "Freaky!",
    "You've got a brand new key!",
    "Water proof!",
    "Uninflammable!",
    "Whoa, dude!",
    "All inclusive!",
    "Tell your friends!",
    "NP is not in P!",
    "Music by C418!",
    "Livestreamed!",
    "Haunted!",
    "Polynomial!",
    "Terrestrial!",
    "All is full of love!",
    "Full of stars!",
    "Scientific!",
    "Not as cool as Spock!",
    "Collaborate and listen!",
    "Never dig down!",
    "Take frequent breaks!",
    "Not linear!",
    "Han shot first!",
    "Nice to meet you!",
    "Buckets of lava!",
    "Ride the pig!",
    "Larger than Earth!",
    "sqrt(-1) love you!",
    "Phobos anomaly!",
    "Punching wood!",
    "Falling off cliffs!",
    "1% sugar!",
    "150% hyperbole!",
    "Synecdoche!",
    "Let's danec!",
    "Seecret Friday update!",
    "Reference implementation!",
    "Kiss the sky!",
    "20 GOTO 10!",
    "Verlet integration!",
    "Peter Griffin!",
    "Do not distribute!",
    "Cogito ergo sum!",
    "4815162342 lines of code!",
    "A skeleton popped out!",
    "The sum of its parts!",
    "BTAF used to be good!",
    "I miss ADOM!",
    "umop-apisdn!",
    "OICU812!",
    "Bring me Ray Cokes!",
    "Finger-licking!",
    "Thematic!",
    "Pneumatic!",
    "Sublime!",
    "Octagonal!",
    "Une baguette!",
    "Gargamel plays it!",
    "Rita is the new top dog!",
    "SWM forever!",
    "Representing Edsbyn!",
    "Matt Damon!",
    "Supercalifragilisticexpialidocious!",
    "Consummate V's!",
    "Cow Tools!",
    "Double buffered!",
    "Fan fiction!",
    "Flaxkikare!",
    "Jason! Jason! Jason!",
    "Hotter than the sun!",
    "Internet enabled!",
    "Autonomous!",
    "Engage!",
    "Fantasy!",
    "DRR! DRR! DRR!",
    "Kick it root down!",
    "Regional resources!",
    "Woo, facepunch!",
    "Woo, somethingawful!",
    "Woo, tigsource!",
    "Woo, worldofminecraft!",
    "Woo, reddit!",
    "Woo, 2pp!",
    "Google anlyticsed!",
    "Now supports åäö!",
    "Give us Gordon!",
    "Tip your waiter!",
    "Very fun!",
    "12345 is a bad password!",
    "Vote for net neutrality!",
    "Lives in a pineapple under the sea!",
    "MAP11 has two names!",
    "Omnipotent!",
    "Gasp!",
    "...!",
    "Bees, bees, bees, bees!",
    "Jag känner en bot!",
    "This text is hard to read if you play the game at the default resolution, but at 1080p it's fine!",
    "Haha, LOL!",
    "Hampsterdance!",
    "Menger sponge!",
    "idspispopd!",
    "Eple (original edit)!",
    "So fresh, so clean!",
    "Slow acting portals!",
    "Try the Nether!",
    "Don't look directly at the bugs!",
    "Oh, ok, Pigmen!",
    "Finally with ladders!",
    "Scary!",
    "Play Minecraft, Watch Topgear, Get Pig!",
    "Twittered about!",
    "Jump up, jump up, and get down!",
    "Joel is neat!",
    "A riddle, wrapped in a mystery!",
    "This parrot is no more! It has ceased to be!",
    "Welcome to your Doom!",
    "Stay a while, stay forever!",
    "Stay a while and listen!",
    "Treatment for your rash!",
    "\"Autological\" is!",
    "Information wants to be free!",
    "\"Almost never\" is an interesting concept!",
    "Lots of truthiness!",
    "The creeper is a spy!",
    "Turing complete!",
    "It's groundbreaking!",
    "Let our battle's begin!",
    "The sky is the limit!",
    "Jeb has amazing hair!",
    "Ryan also has amazing hair!",
    "Casual gaming!",
    "Undefeated!",
    "Kinda like Lemmings!",
    "Follow the train, CJ!",
    "Leveraging synergy!",
    "This message will never appear on the splash screen, isn't that weird?",
    "DungeonQuest is unfair!",
    "90210!",
    "Check out the far lands!",
    "Tyrion would love it!",
    "Also try VVVVVV!",
    "Also try Super Meat Boy!",
    "Also try Terraria!",
    "Also try Mount And Blade!",
    "Also try Project Zomboid!",
    "Also try World of Goo!",
    "Also try Limbo!",
    "Also try Pixeljunk Shooter!",
    "Also try Braid!",
    "That's super!",
    "Bread is pain!",
    "Read more books!",
    "Khaaaaaaaaan!",
    "Less addictive than TV Tropes!",
    "More addictive than lemonade!",
    "Bigger than a bread box!",
    "Millions of peaches!",
    "Fnord!",
    "This is my true form!",
    "Don't bother with the clones!",
    "Pumpkinhead!",
    "Made by Jeb!",
    "Has an ending!",
    "Finally complete!",
    "Feature packed!",
    "Boots with the fur!",
    "Stop, hammertime!",
    "Testificates!",
    "Conventional!",
    "Homeomorphic to a 3-sphere!",
    "Doesn't avoid double negatives!",
    "Place ALL the blocks!",
    "Does barrel rolls!",
    "Meeting expectations!",
    "PC gaming since 1873!",
    "Ghoughpteighbteau tchoghs!",
    "Déjà vu!",
    "Déjà vu!",
    "Got your nose!",
    "Haley loves Elan!",
    "Afraid of the big, black bat!",
    "Doesn't use the U-word!",
    "Child's play!",
    "See you next Friday or so!",
    "From the streets of Södermalm!",
    "150 bpm for 400000 minutes!",
    "Technologic!",
    "Funk soul brother!",
    "Pumpakungen!",
    "日本ハロー！",
    "한국 안녕하세요!",
    "Helo Cymru!",
    "Cześć Polsko!",
    "你好中国！",
    "Γεια σου Ελλάδα!",
    "My life for Aiur!",
    "Lennart lennart = new Lennart();",
    "I see your vocabulary has improved!",
    "Who put it there?",
    "You can't explain that!",
    "if not ok then return end",
    "§1C§2o§3l§4o§5r§6m§7a§8t§9i§ac",
    "§kFUNKY LOL",
    "Big Pointy Teeth!",
    "Bekarton guards the gate!",
    "Mmmph, mmph!",
    "Don't feed avocados to parrots!",
    "Swords for everyone!",
    "Plz reply to my tweet!",
    ".party()!",
    "Take her pillow!",
    "Put that cookie down!",
    "Pretty scary!",
    "I have a suggestion.",
    "Now with extra hugs!",
    "Java 16 + 1 + 4 * 2 = 25!",
    "Woah.",
    "HURNERJSGER?",
    "What's up, Doc?",
    "Now contains 32 random daily cats!",
    "That's Numberwang!",
    "pls rt",
    "Do you want to join my server?",
    "Put a little fence around it!",
    "Throw a blanket over it!",
    "One day, somewhere in the future, my work will be quoted!",
    "Now with additional stuff!",
    "Extra things!",
    "Yay, puppies for everyone!",
    "So sweet, like a nice bon bon!",
    "Very influential in its circle!",
    "Now With Multiplayer!",
    "Rise from your grave!",
    "Warning! A huge battleship \"STEVE\" is approaching fast!",
    "Blue warrior shot the food!",
    "Run, coward! I hunger!",
    "Flavor with no seasoning!",
    "Strange, but not a stranger!",
    "Tougher than diamonds, rich like cream!",
    "It swings, it jives!",
    "Cruising streets for gold!",
    "Take an eggbeater and beat it against a skillet!",
    "Make me a table, a funky table!",
    "Take the elevator to the mezzanine!",
    "Stop being reasonable, this is the Internet!",
    "/give @a hugs 64",
    "This is good for Realms.",
    "Any computer is a laptop if you're brave enough!",
    "Do it all, everything!",
    "Where there is not light, there can spider!",
    "GNU Terry Pratchett",
    "More Digital!",
    "doot doot",
    "Falling with style!",
    "There's no stopping the Trollmaso",
    "Throw yourself at the ground and miss",
    "Rule #1: it's never my fault",
    "Replaced molten cheese with blood?",
    "Absolutely fixed relatively broken coordinates",
    "Boats FTW",
    "Javalicious edition",
    "Should not be played while driving",
    "You're going too fast!",
    "Don't feed chocolate to parrots!",
    "The true meaning of covfefe",
    "An illusion! What are you hiding?",
    "Something's not quite right...",
    "Thank you for the fish!",
    "All rumors are true!",
    "Truly gone fishing!",
    "Rainbow turtle?",
    "Something funny!",
    "I need more context.",
    "Ahhhhhh!",
    "Don't worry, be happy!",
    "Water bottle!",
    "What's the question?",
    "Plant a tree!",
    "Go to the dentist!",
    "What do you expect?",
    "Look mum, I'm in a splash!",
    "It came from space.",
    "Awesome game design right there!",
    "Ph1lza had a good run!",
    "15 years of Mining and Crafting!",
    "Ping the human!",
    "In case it isn't obvious, foxes aren't players.",
    "Buzzy Bees!",
    "Minecraft Java Edition presents: Disgusting Bugs",
    "Wash your hands!",
    "Soap and water!",
    "Support local businesses!",
    "Stay home and play games!",
    "Stay safe!",
    "Stay strong!",
    "Cough or sneeze into your elbow!",
    "Don't touch your face!",
    "Support elderly relatives and friends!",
    "Prepare, but don't hoard!",
    "Gamers unite – separately in your own homes!",
    "Save the world – stay inside!",
    "Shop for your elders!",
    "Hang out with your friends online!",
    "Honey, I grew the bees!",
    "Find your claw!",
    "Everybody do the Leif!",
    "<3 Max & 99 & Ducky!",
    "Bushy eyebrows!",
    "Edit is a name!",
    "From free range developers!",
    "Music by Lena Raine!",
    "Aww man!",
    "#minecraftfarms",
    "And my pickaxe!",
    "Envision! Create! Share!",
    "Fabulous graphics!",
    "Also try Minecraft Dungeons!",
    "Vanilla!",
    "May contain traces of citrus!",
    "Zoglin!?",
    "Black lives matter!",
    "Be anti-racist!",
    "Learn about allyship!",
    "Speak OUT against injustice and UP for equality!",
    "Amplify and listen to BIPOC voices!",
    "Educate your friends on anti-racism!",
    "Support the BIPOC community and creators!",
    "Stand up for equality in your community!",
    "[this splash text is now available]",
    "Contains simulated goats!",
    "Home-made!",
    "There's <<a cat on ,my keyboard!~",
    "The cutest predator you'll ever meet!",
    "Now you are thinking with pistons!",
    "Get to the coppah!",
    "Board game version also available!",
    "Honey, I waxed the copper!",
    "Plant-based light sources!",
    "Made by \"real\" people!",
    "Shriek like a Sculk Shrieker!",
    "Who let the frogs out?",
    "RIBBIT!",
    "Croak team!",
    "Nooooooooooooo!",
    "Flower forest TM perfume",
    "Hat Fridays!",
    "Technoblade never dies!",
    "You are valid!",
    "I'm glad you're here!",
    "You are welcome here!",
    "Your gender is valid!",
    "Contains infinite genders!",
    "Made with lave!",
    "This sand is sus",
    "Remember to brush your... ...teeth",
    "Has working bookshelves!",
    "Sniff sniff...",
    "Place hanging sign here",
    "Joule is neat too!",
    "Music by Aaron Cherof!",
    "Music by Kumi Tanioka!",
    "Music by Amos Roddy!",
    "Flint and Steel!",
    "Chicken Jockey!",
    "One does not simply walk to the Far Lands",
    "Music by Hyper Potions!",
    "Music by fingerspit!"
]

SPLASH_INTERVAL = 60 # in seconds

# death messages
DEATH_MOBS = [
    "Zombie", "Skeleton", "Creeper", "Enderman", "Spider", 
    "Witch", "Wither Skeleton", "Ender Dragon", "Warden"
]
DEATH_ITEMS = [
    "Netherite Sword", "Diamond Axe", "Enchanted Bow", 
    "Knockback Stick", "Wooden Shovel", "Firework Rocket"
]
DEATH_MESSAGES = [
    "{name} was shot by {mob}",
    "{name} was shot by {mob} using {item}",
    "{name} was pricked to death",
    "{name} walked into a cactus while trying to escape {mob}",
    "{name} death.attack.cactus.item",
    "{name} went up in flames",
    "{name} walked into fire while fighting {mob}",
    "{name} death.attack.inFire.item",
    "{name} was squished too much",
    "{name} was squashed by {mob}",
    "{name} death.attack.cramming.item",
    "{name} was roasted in dragon's breath",
    "{name} was roasted in dragon's breath by {mob}",
    "{name} death.attack.dragonBreath.item",
    "{name} drowned",
    "{name} drowned while trying to escape {mob}",
    "{name} death.attack.drown.item",
    "{name} died from dehydration",
    "{name} died from dehydration while trying to escape {mob}",
    "{name} death.attack.dryout.item",
    "{name} hit the ground too hard",
    "{name} hit the ground too hard while trying to escape {mob}",
    "{name} death.attack.fall.item",
    "{name} blew up",
    "{name} was blown up by {mob}",
    "{name} death.attack.explosion.item",
    "{name} was squashed by a falling anvil",
    "{name} was squashed by a falling anvil while fighting {mob}",
    "{name} death.attack.anvil.item",
    "{name} was squashed by a falling block",
    "{name} was squashed by a falling block while fighting {mob}",
    "{name} death.attack.fallingBlock.item",
    "{name} was skewered by a falling stalactite",
    "{name} was skewered by a falling stalactite while fighting {mob}",
    "{name} death.attack.fallingStalactite.item",
    "{name} was fireballed by {mob}",
    "{name} was fireballed by {mob} using {item}",
    "{name} death.attack.fireball.item",
    "{name} went off with a bang",
    "{name} went off with a bang while fighting {mob}",
    "{name} went off with a bang due to a firework fired from {item} by {mob}",
    "{name} experienced kinetic energy",
    "{name} experienced kinetic energy while trying to escape {mob}",
    "{name} death.attack.flyIntoWall.item",
    "{name} froze to death",
    "{name} was frozen to death by {mob}",
    "{name} death.attack.freeze.item",
    "{name} died",
    "{name} died because of {mob}",
    "{name} death.attack.generic.item",
    "{name} was killed",
    "{name} was killed while fighting {mob}",
    "{name} death.attack.genericKill.item",
    "{name} discovered the floor was lava",
    "{name} walked into the danger zone due to {mob}",
    "{name} death.attack.hotFloor.item",
    "{name} suffocated in a wall",
    "{name} suffocated in a wall while fighting {mob}",
    "{name} death.attack.inWall.item",
    "{name} was killed by {mob} using magic",
    "{name} death.attack.indirectMagic.player",
    "{name} was killed by {mob} using {item}",
    "{name} was killed by magic",
    "{name} was killed by magic while trying to escape {mob}",
    "{name} death.attack.magic.item",
    "{name} tried to swim in lava",
    "{name} tried to swim in lava to escape {mob}",
    "{name} death.attack.lava.item",
    "{name} was struck by lightning",
    "{name} was struck by lightning while fighting {mob}",
    "{name} death.attack.lightningBolt.item",
    "{name} was smashed by {mob}",
    "{name} death.attack.mace_smash.player",
    "{name} was smashed by {mob} with {item}",
    "{name} was slain by {mob}",
    "{name} death.attack.mob.player",
    "{name} was slain by {mob} using {item}",
    "{name} burned to death",
    "{name} was burned to a crisp while fighting {mob}",
    "{name} was burned to a crisp while fighting {mob} wielding {item}",
    "{name} fell out of the world",
    "{name} didn't want to live in the same world as {mob}",
    "{name} death.attack.outOfWorld.item",
    "{name} left the confines of this world",
    "{name} left the confines of this world while fighting {mob}",
    "{name} death.attack.outsideBorder.item",
    "{name} was blown up by {mob}",
    "{name} death.attack.explosion.player.player",
    "{name} was obliterated by a sonically-charged shriek",
    "{name} was obliterated by a sonically-charged shriek while trying to escape {mob}",
    "{name} was obliterated by a sonically-charged shriek while trying to escape {mob} wielding {item}",
    "{name} was speared by {mob}",
    "{name} death.attack.spear.player",
    "{name} was speared by {mob} using {item}",
    "{name} was pummeled by {mob}",
    "{name} death.attack.thrown.player",
    "{name} was pummeled by {mob} using {item}",
    "{name} was impaled on a stalagmite",
    "{name} was impaled on a stalagmite while fighting {mob}",
    "{name} death.attack.stalagmite.item",
    "{name} starved to death",
    "{name} starved to death while fighting {mob}",
    "{name} death.attack.starve.item",
    "{name} was stung to death",
    "{name} was stung to death by {mob}",
    "{name} was stung to death by {mob} using {item}",
    "{name} died because not just the floor is lava",
    "{mob} showed {name} that not just the floor is lava",
    "{name} death.attack.sulfurCubeHot.item",
    "{name} was poked to death by a sweet berry bush",
    "{name} was poked to death by a sweet berry bush while trying to escape {mob}",
    "{name} death.attack.sweetBerryBush.item",
    "{name} was killed while trying to hurt {mob}",
    "{name} death.attack.thorns.player",
    "{name} was killed by {item} while trying to hurt {mob}",
    "{name} was impaled by {mob}",
    "{name} death.attack.trident.player",
    "{name} was impaled by {mob} with {item}",
    "{name} withered away",
    "{name} withered away while fighting {mob}",
    "{name} death.attack.wither.item",
    "{name} was shot by a skull from {mob}",
    "{name} death.attack.witherSkull.player",
    "{name} was shot by a skull from {mob} using {item}"
]